### ISSUE TITLE
Does this work with OTG USB?

### ISSUE THREAD

**Issue by galebnas** [brtperry/AndroidPayment#1]
Thank you very much for this repository, I have a Verifone VX 520g device and I want to connect it to my android tablet via USB will this work and could you provide more information

Thanks

**Comment by brtperry** [comment]
Hi, this repository was designed to talk to a Verifone VX820 and VX680 over a IP network using sockets.  Does your OTG USB device publish an IP address?

**Comment by galebnas** [comment]
Thank you for the quick reply,
My device is Verifone VX 520g and I am trying to connect it to an android tablet to initiate transactions with specific amount then listen to (or wait for) the result (success or failure) and retrieve the transaction id in case of success.
I was thinking of connecting the Verifone device via a USB OTG cable but I am open to other suggestions like connecting both the Verifone device and the android tablet to a network and use sockets.

I would appreciate your help with this.

**Comment by brtperry** [comment]
Hi, I've not used or tested with a USB OTG cable, therefore I can only suggest using a network.

You'll need to send a logon record which goes something like this: "L2," + username + "," + password + ",2 {2 {*}} 4\r\n";

**Comment by galebnas** [comment]
hmm, So I can use your code with my Verifone VX 520g? I just have to change the logon record
Can I find this instruction somewhere like a manual or something

**Comment by brtperry** [comment]
Not sure about the manuals, but make sure you can connect on the socket and then send this string "L2,1234,1234,4\r\n" replacing '1234' with your username and password credentials.  It's been awhile since I've used this code.  I've got a bunch of .java files that may help.  I'll commit them.

**Comment by brtperry** [comment]
Added some more files to the master branch for you, they may help :)

**Comment by galebnas** [comment]
Great thank you very much for your help, I will review the new files and get back to you :)
